### ISSUE TITLE
Call a MF after clicking on tab page

### ISSUE THREAD

**Issue by rover886** [mendixlabs/TabPageSelector#2]
Right now when we click on tab page current tab page number is getting updated in selected attribute. It would be nice if along with that a MF should also get called.

**Comment by rover886** [comment]
But, right now due a [limitation ](https://forum.mendix.com/link/space/widgets/questions/95035) from Mendix, widgets can call MF but without parameter. 

Will that make seance to call a MF without any parameter ? More clarity would help to understand the use case.

**Comment by bsgriggs** [comment]
Hi Rover, you do not need to set a parameter for actions in the pluggable widget API. It will automatically apply the widget's context. I was making a similar widget until I found yours.

In my example, I have the widget inside a data view.
![Screenshot 2023-07-12 at 11 38 58 AM](https://github.com/mendixlabs/TabPageSelector/assets/47681665/fbfa1afb-dbf9-47cd-b043-aa8d11079e8b)
The microflow has a parameter that matches the object in the parent data view. As you can see, the microflow gets the updated tab index.
![Screenshot 2023-07-12 at 11 30 22 AM](https://github.com/mendixlabs/TabPageSelector/assets/47681665/501a064f-2bdd-4c67-a1b9-848061803022)

If you can add an action, then the developer can add an on-click microflow and simply check the attribute on the parent object to determine which tab was clicked.
![Screenshot 2023-07-12 at 11 29 46 AM](https://github.com/mendixlabs/TabPageSelector/assets/47681665/5287d06c-1e63-4af2-bf7a-3133b3419736)
 You would then call the action when the tab is clicked
![Screenshot 2023-07-12 at 11 29 37 AM](https://github.com/mendixlabs/TabPageSelector/assets/47681665/582d23cf-40ff-496a-8397-37afff7c4527)


I would add myself and make a pull request, but I'm a little scared of class components :P. [Here](https://github.com/bsgriggs/mendix-tab-container-actions) is my example if you're curious.

**Comment by rover886** [comment]
Hi @bsgriggs Thanks for taking time to looking into this repo and also in issue. Thanks for guiding me in this regard.
